server:
  port: 8080
spring:
  mail:
    host: smtp.gmail.com
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true # Enable STARTTLS
  application:
    name: enkore_karaoke
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: ${DB_URL:jdbc:mysql://localhost:3306/enkore_karaoke?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true}
      username: ${DB_USERNAME:root}
      password: ${DB_PASSWORD:}
mybatis-plus:
  configuration:
    # When mapping entities or attributes, remove the underscores in the table names and field names in the database and map according to the camel case nomenclature.
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
enkore:
  path: ${ENKORE_UPLOAD_PATH:uploads/}
