server:
  port: 8080
spring:
  mail:
    host: smtp.gmail.com
    username: thisisjohn1013@gmail.com
    password: ngrqnmpazrolbfcf
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true # Enable STARTTLS
  application:
    name: enkore_karaoke
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/enkore_karaoke?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 110120119
mybatis-plus:
  configuration:
    # When mapping entities or attributes, remove the underscores in the table names and field names in the database and map according to the camel case nomenclature.
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
enkore:
  path: /Users/john/IdeaProjects/enkore/src/main/resources/imag/